// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD19kE9VH5xFzfmBBnlxZHrUB_tJ3g5sD8',
    appId: '1:909657020571:web:c61a4ed649050f8e8c8e3e',
    messagingSenderId: '909657020571',
    projectId: 'todo-app-a3d77',
    authDomain: 'todo-app-a3d77.firebaseapp.com',
    storageBucket: 'todo-app-a3d77.appspot.com',
    measurementId: 'G-9WCSLGYSBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2czTJcVEnEStOPclk3kFGoAgm80us-rk',
    appId: '1:909657020571:android:5e319cbb388905658c8e3e',
    messagingSenderId: '909657020571',
    projectId: 'todo-app-a3d77',
    storageBucket: 'todo-app-a3d77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAXx1_Fe34x7ZKNs5GArO7_IIItf1cOXU',
    appId: '1:909657020571:ios:ebfc223fac4cef158c8e3e',
    messagingSenderId: '909657020571',
    projectId: 'todo-app-a3d77',
    storageBucket: 'todo-app-a3d77.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAXx1_Fe34x7ZKNs5GArO7_IIItf1cOXU',
    appId: '1:909657020571:ios:ebfc223fac4cef158c8e3e',
    messagingSenderId: '909657020571',
    projectId: 'todo-app-a3d77',
    storageBucket: 'todo-app-a3d77.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD19kE9VH5xFzfmBBnlxZHrUB_tJ3g5sD8',
    appId: '1:909657020571:web:987fb1ad97b31f678c8e3e',
    messagingSenderId: '909657020571',
    projectId: 'todo-app-a3d77',
    authDomain: 'todo-app-a3d77.firebaseapp.com',
    storageBucket: 'todo-app-a3d77.appspot.com',
    measurementId: 'G-2S1F9XLDWR',
  );
}
